name: Website check

on:
  push:    # This triggers the workflow on push to the repository
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes

jobs:
  check-websites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  
      - run: npm install  
      - run: node serverupcheck.js
